services:
  - type: web
    name: game-cgbshop1
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_WOOCOMMERCE_URL
        sync: false
      - key: VITE_CONSUMER_KEY
        sync: false
      - key: VITE_CONSUMER_SECRET
        sync: false