services:
  - type: web
    name: game-cgbshop1
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    nodeVersion: 18.x